const Images: { [key: string]: any } = {
	UI: {
		playIcon: require('../../assets/images/play.png'),
		loadingPiece: require('../../assets/images/piece.png'),
		arrowIcon: require('../../assets/images/arrow.png'),
	},
	lottieLoading: require('../../assets/lottie/squares.json'),
	bullfinch: {
		cover: require('../../assets/images/bullfinch/bullfinch.png'),
		11: require('../../assets/images/bullfinch/11.png'),
		12: require('../../assets/images/bullfinch/12.png'),
		13: require('../../assets/images/bullfinch/13.png'),
		21: require('../../assets/images/bullfinch/21.png'),
		22: require('../../assets/images/bullfinch/22.png'),
		23: require('../../assets/images/bullfinch/23.png'),
		31: require('../../assets/images/bullfinch/31.png'),
		32: require('../../assets/images/bullfinch/32.png'),
		33: require('../../assets/images/bullfinch/33.png'),
		41: require('../../assets/images/bullfinch/41.png'),
		42: require('../../assets/images/bullfinch/42.png'),
		43: require('../../assets/images/bullfinch/43.png'),
	},
	shiba: {
		cover: require('../../assets/images/shiba/shiba.png'),
		11: require('../../assets/images/shiba/11.png'),
		12: require('../../assets/images/shiba/12.png'),
		13: require('../../assets/images/shiba/13.png'),
		21: require('../../assets/images/shiba/21.png'),
		22: require('../../assets/images/shiba/22.png'),
		23: require('../../assets/images/shiba/23.png'),
		31: require('../../assets/images/shiba/31.png'),
		32: require('../../assets/images/shiba/32.png'),
		33: require('../../assets/images/shiba/33.png'),
		41: require('../../assets/images/shiba/41.png'),
		42: require('../../assets/images/shiba/42.png'),
		43: require('../../assets/images/shiba/43.png'),
	},
	house: {
		cover: require('../../assets/images/house/house.png'),
		11: require('../../assets/images/house/11.png'),
		12: require('../../assets/images/house/12.png'),
		13: require('../../assets/images/house/13.png'),
		21: require('../../assets/images/house/21.png'),
		22: require('../../assets/images/house/22.png'),
		23: require('../../assets/images/house/23.png'),
		31: require('../../assets/images/house/31.png'),
		32: require('../../assets/images/house/32.png'),
		33: require('../../assets/images/house/33.png'),
		41: require('../../assets/images/house/41.png'),
		42: require('../../assets/images/house/42.png'),
		43: require('../../assets/images/house/43.png'),
	},
};

export default Images;
